/** LinkedIn Search SRP facet IDs — same keys Sales Nav / Hunter Discover paint. */

export const COMPANY_SIZES = [
  { id: "B", label: "1–10" },
  { id: "C", label: "11–50" },
  { id: "D", label: "51–200" },
  { id: "E", label: "201–500" },
  { id: "F", label: "501–1,000" },
  { id: "G", label: "1,001–5,000" },
  { id: "H", label: "5,001–10,000" },
  { id: "I", label: "10,001+" },
] as const;

export const COMPANY_TYPES = [
  { id: "Public Company", label: "Public Company" },
  { id: "Privately Held", label: "Privately Held" },
  { id: "Nonprofit", label: "Nonprofit" },
  { id: "Educational Institution", label: "Educational" },
  { id: "Partnership", label: "Partnership" },
  { id: "Government Agency", label: "Government" },
  { id: "Self-Employed", label: "Self-employed" },
  { id: "Sole Proprietorship", label: "Sole proprietorship" },
] as const;

export const LANGUAGES = [
  { id: "en", label: "English" },
  { id: "es", label: "Spanish" },
  { id: "fr", label: "French" },
  { id: "de", label: "German" },
  { id: "pt", label: "Portuguese" },
  { id: "zh", label: "Chinese" },
  { id: "hi", label: "Hindi" },
  { id: "ar", label: "Arabic" },
  { id: "ja", label: "Japanese" },
  { id: "ko", label: "Korean" },
  { id: "it", label: "Italian" },
  { id: "nl", label: "Dutch" },
  { id: "tr", label: "Turkish" },
  { id: "pl", label: "Polish" },
  { id: "ru", label: "Russian" },
  { id: "sv", label: "Swedish" },
  { id: "id", label: "Indonesian" },
] as const;

export const YEARS_EXPERIENCE = [
  { id: "intern junior", label: "0–2 years" },
  { id: "mid-level", label: "3–5 years" },
  { id: "senior", label: "6–10 years" },
  { id: "lead principal", label: "10–15 years" },
  { id: "director VP chief", label: "15+ years" },
] as const;

export const TENURE = [
  { id: "1 year", label: "< 1 year" },
  { id: "2 years", label: "1–2 years" },
  { id: "3 years", label: "3–5 years" },
  { id: "5 years", label: "5–10 years" },
  { id: "10 years", label: "10+ years" },
] as const;

/** Title shards — used to pull named people past LinkedIn’s Member wall. */
export const TITLE_SHARDS = [
  "Engineer",
  "Manager",
  "Director",
  "Consultant",
  "Analyst",
  "Designer",
  "Scientist",
  "Coordinator",
  "Specialist",
  "Advisor",
  "Marketing",
  "Sales",
  "Finance",
  "Human Resources",
  "Operations",
  "Project",
  "Principal",
  "Partner",
  "President",
  "Chief",
] as const;

export const GEO_COUNTRIES = [
  { id: "103644278", label: "United States" },
  { id: "101165590", label: "United Kingdom" },
  { id: "101452733", label: "Australia" },
  { id: "101174742", label: "Canada" },
  { id: "102713980", label: "India" },
  { id: "101282230", label: "Germany" },
  { id: "105015875", label: "France" },
  { id: "103350119", label: "Italy" },
  { id: "105646813", label: "Spain" },
  { id: "102890719", label: "Netherlands" },
  { id: "102454443", label: "Singapore" },
  { id: "104305776", label: "United Arab Emirates" },
  { id: "105490917", label: "New Zealand" },
  { id: "104738515", label: "Ireland" },
  { id: "104035573", label: "South Africa" },
  { id: "106057199", label: "Brazil" },
  { id: "101355337", label: "Japan" },
  { id: "103323778", label: "Mexico" },
  { id: "105117694", label: "Sweden" },
  { id: "106693272", label: "Switzerland" },
  { id: "103291313", label: "Hong Kong" },
  { id: "103121230", label: "Philippines" },
  { id: "102478259", label: "Indonesia" },
  { id: "102095887", label: "Malaysia" },
  { id: "101282345", label: "Belgium" },
  { id: "104677530", label: "Austria" },
  { id: "104514075", label: "Denmark" },
  { id: "105072130", label: "Norway" },
  { id: "100364837", label: "Finland" },
  { id: "104588865", label: "Poland" },
] as const;

export const INDUSTRIES = [
  { id: "96", label: "IT Services and IT Consulting" },
  { id: "4", label: "Computer Software" },
  { id: "6", label: "Information Technology" },
  { id: "51", label: "Civil Engineering" },
  { id: "48", label: "Construction" },
  { id: "47", label: "Architecture and Planning" },
  { id: "11", label: "Management Consulting" },
  { id: "80", label: "Business Consulting and Services" },
  { id: "43", label: "Financial Services" },
  { id: "41", label: "Banking" },
  { id: "42", label: "Insurance" },
  { id: "14", label: "Hospitals and Health Care" },
  { id: "15", label: "Pharmaceuticals" },
  { id: "13", label: "Biotechnology" },
  { id: "25", label: "Consumer Goods" },
  { id: "27", label: "Retail" },
  { id: "31", label: "Real Estate" },
  { id: "52", label: "Higher Education" },
  { id: "68", label: "Education Administration" },
  { id: "8", label: "Internet" },
  { id: "24", label: "Marketing and Advertising" },
  { id: "34", label: "Staffing and Recruiting" },
  { id: "9", label: "Telecommunications" },
  { id: "53", label: "Legal Services" },
  { id: "54", label: "Law Practice" },
  { id: "137", label: "Human Resources" },
  { id: "7", label: "Computer Hardware" },
  { id: "28", label: "Consumer Services" },
  { id: "116", label: "Manufacturing" },
  { id: "44", label: "Oil and Energy" },
  { id: "57", label: "Government Administration" },
  { id: "75", label: "Nonprofit" },
  { id: "99", label: "Environmental Services" },
  { id: "135", label: "Mechanical or Industrial Engineering" },
  { id: "3249", label: "Engineering Services" },
  { id: "55", label: "Design" },
  { id: "112", label: "Utilities" },
  { id: "36", label: "Logistics and Supply Chain" },
  { id: "26", label: "Wholesale" },
  { id: "33", label: "Mining" },
] as const;

export const LINKEDIN_FUNCTIONS = [
  "Accounting",
  "Administrative",
  "Arts and Design",
  "Business Development",
  "Community and Social Services",
  "Consulting",
  "Education",
  "Engineering",
  "Entrepreneurship",
  "Finance",
  "Healthcare Services",
  "Human Resources",
  "Information Technology",
  "Legal",
  "Marketing",
  "Media and Communication",
  "Military and Protective Services",
  "Operations",
  "Product Management",
  "Program and Project Management",
  "Purchasing",
  "Quality Assurance",
  "Real Estate",
  "Research",
  "Sales",
  "Support",
] as const;
