/** Google Places Table A–style types used by Maps lead finders (~196). */
export const MAPS_TYPES: { id: string; label: string; osm: string }[] = [
  { id: "accounting", label: "Accounting", osm: "accountant" },
  { id: "airport", label: "Airport", osm: "aerodrome" },
  { id: "amusement_park", label: "Amusement park", osm: "theme_park" },
  { id: "aquarium", label: "Aquarium", osm: "aquarium" },
  { id: "art_gallery", label: "Art gallery", osm: "art_gallery" },
  { id: "atm", label: "ATM", osm: "atm" },
  { id: "bakery", label: "Bakery", osm: "bakery" },
  { id: "bank", label: "Bank", osm: "bank" },
  { id: "bar", label: "Bar", osm: "bar" },
  { id: "beauty_salon", label: "Beauty salon", osm: "beauty" },
  { id: "bicycle_store", label: "Bicycle store", osm: "bicycle" },
  { id: "book_store", label: "Book store", osm: "books" },
  { id: "bowling_alley", label: "Bowling alley", osm: "bowling" },
  { id: "bus_station", label: "Bus station", osm: "bus_station" },
  { id: "cafe", label: "Cafe", osm: "cafe" },
  { id: "campground", label: "Campground", osm: "camp_site" },
  { id: "car_dealer", label: "Car dealer", osm: "car" },
  { id: "car_rental", label: "Car rental", osm: "car_rental" },
  { id: "car_repair", label: "Car repair", osm: "car_repair" },
  { id: "car_wash", label: "Car wash", osm: "car_wash" },
  { id: "casino", label: "Casino", osm: "casino" },
  { id: "cemetery", label: "Cemetery", osm: "grave_yard" },
  { id: "church", label: "Church", osm: "christian" },
  { id: "city_hall", label: "City hall", osm: "townhall" },
  { id: "clothing_store", label: "Clothing store", osm: "clothes" },
  { id: "convenience_store", label: "Convenience store", osm: "convenience" },
  { id: "courthouse", label: "Courthouse", osm: "courthouse" },
  { id: "dentist", label: "Dentist", osm: "dentist" },
  { id: "department_store", label: "Department store", osm: "department_store" },
  { id: "doctor", label: "Doctor", osm: "doctors" },
  { id: "drugstore", label: "Drugstore", osm: "chemist" },
  { id: "electrician", label: "Electrician", osm: "electrician" },
  { id: "electronics_store", label: "Electronics store", osm: "electronics" },
  { id: "embassy", label: "Embassy", osm: "embassy" },
  { id: "fire_station", label: "Fire station", osm: "fire_station" },
  { id: "florist", label: "Florist", osm: "florist" },
  { id: "funeral_home", label: "Funeral home", osm: "funeral_directors" },
  { id: "furniture_store", label: "Furniture store", osm: "furniture" },
  { id: "gas_station", label: "Gas station", osm: "fuel" },
  { id: "gym", label: "Gym", osm: "fitness_centre" },
  { id: "hair_care", label: "Hair care", osm: "hairdresser" },
  { id: "hardware_store", label: "Hardware store", osm: "doityourself" },
  { id: "hindu_temple", label: "Hindu temple", osm: "hindu" },
  { id: "home_goods_store", label: "Home goods store", osm: "houseware" },
  { id: "hospital", label: "Hospital", osm: "hospital" },
  { id: "insurance_agency", label: "Insurance agency", osm: "insurance" },
  { id: "jewelry_store", label: "Jewelry store", osm: "jewelry" },
  { id: "laundry", label: "Laundry", osm: "laundry" },
  { id: "lawyer", label: "Lawyer", osm: "lawyer" },
  { id: "library", label: "Library", osm: "library" },
  { id: "liquor_store", label: "Liquor store", osm: "alcohol" },
  { id: "local_government_office", label: "Local government office", osm: "government" },
  { id: "locksmith", label: "Locksmith", osm: "locksmith" },
  { id: "lodging", label: "Lodging", osm: "hotel" },
  { id: "meal_delivery", label: "Meal delivery", osm: "fast_food" },
  { id: "meal_takeaway", label: "Meal takeaway", osm: "fast_food" },
  { id: "mosque", label: "Mosque", osm: "muslim" },
  { id: "movie_theater", label: "Movie theater", osm: "cinema" },
  { id: "moving_company", label: "Moving company", osm: "storage_rental" },
  { id: "museum", label: "Museum", osm: "museum" },
  { id: "night_club", label: "Night club", osm: "nightclub" },
  { id: "painter", label: "Painter", osm: "painter" },
  { id: "park", label: "Park", osm: "park" },
  { id: "parking", label: "Parking", osm: "parking" },
  { id: "pet_store", label: "Pet store", osm: "pet" },
  { id: "pharmacy", label: "Pharmacy", osm: "pharmacy" },
  { id: "physiotherapist", label: "Physiotherapist", osm: "physiotherapist" },
  { id: "plumber", label: "Plumber", osm: "plumber" },
  { id: "police", label: "Police", osm: "police" },
  { id: "post_office", label: "Post office", osm: "post_office" },
  { id: "primary_school", label: "Primary school", osm: "school" },
  { id: "real_estate_agency", label: "Real estate agency", osm: "estate_agent" },
  { id: "restaurant", label: "Restaurant", osm: "restaurant" },
  { id: "roofing_contractor", label: "Roofing contractor", osm: "craft" },
  { id: "school", label: "School", osm: "school" },
  { id: "secondary_school", label: "Secondary school", osm: "school" },
  { id: "shoe_store", label: "Shoe store", osm: "shoes" },
  { id: "shopping_mall", label: "Shopping mall", osm: "mall" },
  { id: "spa", label: "Spa", osm: "spa" },
  { id: "stadium", label: "Stadium", osm: "stadium" },
  { id: "storage", label: "Storage", osm: "storage_rental" },
  { id: "store", label: "Store", osm: "supermarket" },
  { id: "supermarket", label: "Supermarket", osm: "supermarket" },
  { id: "synagogue", label: "Synagogue", osm: "jewish" },
  { id: "taxi_stand", label: "Taxi stand", osm: "taxi" },
  { id: "tourist_attraction", label: "Tourist attraction", osm: "attraction" },
  { id: "train_station", label: "Train station", osm: "station" },
  { id: "travel_agency", label: "Travel agency", osm: "travel_agency" },
  { id: "university", label: "University", osm: "university" },
  { id: "veterinary_care", label: "Veterinary care", osm: "veterinary" },
  { id: "zoo", label: "Zoo", osm: "zoo" },
  { id: "american_restaurant", label: "American restaurant", osm: "restaurant" },
  { id: "italian_restaurant", label: "Italian restaurant", osm: "italian" },
  { id: "chinese_restaurant", label: "Chinese restaurant", osm: "chinese" },
  { id: "indian_restaurant", label: "Indian restaurant", osm: "indian" },
  { id: "mexican_restaurant", label: "Mexican restaurant", osm: "mexican" },
  { id: "japanese_restaurant", label: "Japanese restaurant", osm: "japanese" },
  { id: "thai_restaurant", label: "Thai restaurant", osm: "thai" },
  { id: "pizza_restaurant", label: "Pizza restaurant", osm: "pizza" },
  { id: "seafood_restaurant", label: "Seafood restaurant", osm: "seafood" },
  { id: "steak_house", label: "Steak house", osm: "steak" },
  { id: "sushi_restaurant", label: "Sushi restaurant", osm: "sushi" },
  { id: "vegetarian_restaurant", label: "Vegetarian restaurant", osm: "vegetarian" },
  { id: "fast_food_restaurant", label: "Fast food restaurant", osm: "fast_food" },
  { id: "coffee_shop", label: "Coffee shop", osm: "cafe" },
  { id: "bar_and_grill", label: "Bar and grill", osm: "pub" },
  { id: "wine_bar", label: "Wine bar", osm: "wine" },
  { id: "brewery", label: "Brewery", osm: "brewery" },
  { id: "hotel", label: "Hotel", osm: "hotel" },
  { id: "motel", label: "Motel", osm: "motel" },
  { id: "bed_and_breakfast", label: "Bed and breakfast", osm: "guest_house" },
  { id: "resort_hotel", label: "Resort hotel", osm: "resort" },
  { id: "apartment_building", label: "Apartment building", osm: "apartments" },
  { id: "real_estate", label: "Real estate", osm: "estate_agent" },
  { id: "general_contractor", label: "General contractor", osm: "construction" },
  { id: "hvac_contractor", label: "HVAC contractor", osm: "hvac" },
  { id: "landscaper", label: "Landscaper", osm: "garden_centre" },
  { id: "auto_parts_store", label: "Auto parts store", osm: "car_parts" },
  { id: "tire_shop", label: "Tire shop", osm: "tyres" },
  { id: "car_wash", label: "Car wash", osm: "car_wash" },
  { id: "parking_garage", label: "Parking garage", osm: "parking" },
  { id: "electric_vehicle_charging_station", label: "EV charging station", osm: "charging_station" },
  { id: "pharmacy", label: "Pharmacy", osm: "pharmacy" },
  { id: "medical_lab", label: "Medical lab", osm: "laboratory" },
  { id: "dentist", label: "Dentist", osm: "dentist" },
  { id: "chiropractor", label: "Chiropractor", osm: "chiropractor" },
  { id: "optometrist", label: "Optometrist", osm: "optician" },
  { id: "skin_care_clinic", label: "Skin care clinic", osm: "clinic" },
  { id: "hospital", label: "Hospital", osm: "hospital" },
  { id: "clinic", label: "Clinic", osm: "clinic" },
  { id: "nursing_home", label: "Nursing home", osm: "nursing_home" },
  { id: "preschool", label: "Preschool", osm: "kindergarten" },
  { id: "tutoring_center", label: "Tutoring center", osm: "school" },
  { id: "community_center", label: "Community center", osm: "community_centre" },
  { id: "coworking_space", label: "Coworking space", osm: "coworking" },
  { id: "consultant", label: "Consultant", osm: "company" },
  { id: "software_company", label: "Software company", osm: "it" },
  { id: "marketing_agency", label: "Marketing agency", osm: "advertising" },
  { id: "advertising_agency", label: "Advertising agency", osm: "advertising" },
  { id: "courier_service", label: "Courier service", osm: "post_office" },
  { id: "warehouse", label: "Warehouse", osm: "warehouse" },
  { id: "wholesaler", label: "Wholesaler", osm: "wholesale" },
  { id: "manufacturer", label: "Manufacturer", osm: "factory" },
  { id: "farm", label: "Farm", osm: "farm" },
  { id: "golf_course", label: "Golf course", osm: "golf_course" },
  { id: "fitness_center", label: "Fitness center", osm: "fitness_centre" },
  { id: "yoga_studio", label: "Yoga studio", osm: "yoga" },
  { id: "nail_salon", label: "Nail salon", osm: "beauty" },
  { id: "tattoo_shop", label: "Tattoo shop", osm: "tattoo" },
  { id: "barber_shop", label: "Barber shop", osm: "barber" },
  { id: "dry_cleaner", label: "Dry cleaner", osm: "dry_cleaning" },
  { id: "tailor", label: "Tailor", osm: "tailor" },
  { id: "photographer", label: "Photographer", osm: "photo" },
  { id: "event_venue", label: "Event venue", osm: "events_venue" },
  { id: "wedding_venue", label: "Wedding venue", osm: "events_venue" },
  { id: "banquet_hall", label: "Banquet hall", osm: "events_venue" },
  { id: "concert_hall", label: "Concert hall", osm: "theatre" },
  { id: "performing_arts_theater", label: "Performing arts theater", osm: "theatre" },
  { id: "art_studio", label: "Art studio", osm: "studio" },
  { id: "music_school", label: "Music school", osm: "music_school" },
  { id: "dance_school", label: "Dance school", osm: "dancing_school" },
  { id: "language_school", label: "Language school", osm: "language_school" },
  { id: "driving_school", label: "Driving school", osm: "driving_school" },
  { id: "cell_phone_store", label: "Cell phone store", osm: "mobile_phone" },
  { id: "computer_store", label: "Computer store", osm: "computer" },
  { id: "gift_shop", label: "Gift shop", osm: "gift" },
  { id: "florist", label: "Florist", osm: "florist" },
  { id: "garden_center", label: "Garden center", osm: "garden_centre" },
  { id: "hardware_store", label: "Hardware store", osm: "doityourself" },
  { id: "home_improvement_store", label: "Home improvement store", osm: "doityourself" },
  { id: "furniture_store", label: "Furniture store", osm: "furniture" },
  { id: "mattress_store", label: "Mattress store", osm: "bed" },
  { id: "appliance_store", label: "Appliance store", osm: "appliance" },
  { id: "sporting_goods_store", label: "Sporting goods store", osm: "sports" },
  { id: "toy_store", label: "Toy store", osm: "toys" },
  { id: "pet_store", label: "Pet store", osm: "pet" },
  { id: "veterinarian", label: "Veterinarian", osm: "veterinary" },
  { id: "grocery_store", label: "Grocery store", osm: "supermarket" },
  { id: "butcher_shop", label: "Butcher shop", osm: "butcher" },
  { id: "seafood_market", label: "Seafood market", osm: "seafood" },
  { id: "farmers_market", label: "Farmers market", osm: "marketplace" },
  { id: "convenience_store", label: "Convenience store", osm: "convenience" },
  { id: "dollar_store", label: "Dollar store", osm: "variety_store" },
  { id: "thrift_store", label: "Thrift store", osm: "second_hand" },
  { id: "jewelry_store", label: "Jewelry store", osm: "jewelry" },
  { id: "watch_store", label: "Watch store", osm: "watches" },
  { id: "cosmetics_store", label: "Cosmetics store", osm: "cosmetics" },
  { id: "department_store", label: "Department store", osm: "department_store" },
  { id: "shopping_mall", label: "Shopping mall", osm: "mall" },
  { id: "market", label: "Market", osm: "marketplace" },
];

export const UNIQUE_MAPS_TYPES = MAPS_TYPES.filter(
  (t, i, a) => a.findIndex((x) => x.id === t.id) === i,
);
